version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
clone_depth: 5
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
install:
- ps: "if($($env:APPVEYOR))\n{\n \n$firstCommit = $(git log --pretty=format:'%H' -n -1).Length;\n$firstCommitHash = $(git log --pretty=format:'%H' -n -1)[$firstCommit-1];\nWrite-Host \"First Commit Hash:\" $firstCommitHash;\n$firstCommitDate = (git show -s --format=%ci $firstCommitHash);\nWrite-Host \"First Commit Date:\" $firstCommitDate;\n[datetime]$FCDateTime = $firstCommitDate;\n#Write-Host $FCDateTime\n$FCyear = $FCDateTime.ToString(\"y.\").TrimEnd('.');\n#Write-Host $FCyear\n$timeZone0 = [TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, \"Turkey Standard Time\");\n$timeZone = $timeZone0;\n[datetime]$DateTime = $timeZone;\n\n$year = $DateTime.ToString(\"y.\").TrimEnd('.');\n$month = $DateTime.ToString(\"M.\").TrimEnd('.');\n$day = $DateTime.ToString(\"d.\").TrimEnd('.');\n$hourMinute = $DateTime.ToString(\".hmm\").TrimStart('.');\n$buildYear = (($year - $FCyear) + 1);\n#$buildTime = $DateTime.ToString(\"M.d.hmm\");\n$newBuildNumber = \"$buildYear.$month.$day.$hourMinute\";\n\nWrite-Host \"New Nuget Package Version:\" $newBuildNumber\n\nUpdate-AppveyorBuild -Version $newBuildNumber;\n}\nelse\n{\n    Write-Host \"AppVeyor was not detected\";\n}"
cache: packages
build_script:
- ps: "if($($env:APPVEYOR))\n{ \n    $SVersion = $($env:APPVEYOR_BUILD_VERSION);\n    Write-Host \"$($env:APPVEYOR_PROJECT_NAME) Version:$SVersion\";\n \n.\\nuget restore\ndotnet restore\ndotnet clean -c Release\ndotnet build -c Release  /p:Version=$newBuildNumber --framework netcoreapp1.1\n.\\nuget pack -version $newBuildNumber\n\n    Push-AppveyorArtifact \"$($env:APPVEYOR_BUILD_FOLDER)\\$($env:APPVEYOR_PROJECT_NAME).$SVersion.nupkg\" -FileName \"$($env:APPVEYOR_PROJECT_NAME).$SVersion.nupkg\" -DeploymentName \"NugetPackage1\";\n}\nelse\n{\n    Write-Host \"AppVeyor was not detected\";\n}"
test: off